// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow():Promise<void>;

export function GetClipboard():Promise<string>;

export function GetVersion():Promise<string>;

export function IsServerRunning():Promise<boolean>;

export function IsWindowMaximized():Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function SaveNFOFileDialog(arg1:string,arg2:string):Promise<string>;

export function SetClipboard(arg1:string):Promise<void>;

export function StartServer(arg1:number):Promise<boolean>;

export function StopServer():Promise<boolean>;

export function ToggleMaximizeWindow():Promise<boolean>;
