// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function SaveNFOFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveNFOFileDialog'](arg1, arg2);
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}
